"""Aggregate Phase1 shard CSVs (ccx_phase1_shard*.csv) → final 4 CSVs.

Handles both:
  - new shards: colab/shards/ccx_phase1_shard*.csv or results/raw/phase1/ccx_phase1_*.csv
  - legacy per-batch raw: results/raw/phase1/uniform_batch_*.csv etc

Produces the same 4 outputs as enumeration.py tail:
  results/phase1_enumeration/{t1_dictionary.csv, hierarchy_placement.csv,
                               strictness_scan.csv, witness_lp_redundancy.csv}
plus facets cache is reused (already generated by shards or locally).

Deterministic: same seeds → identical numbers.
"""
import json
from pathlib import Path
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RAW = ROOT / "results" / "raw" / "phase1"
RES = ROOT / "results" / "phase1_enumeration"

def load_shards():
    # prefer shard-combined files, fallback to per-batch
    shard_files = sorted(RAW.glob("ccx_phase1_shard*.csv"))
    if shard_files:
        print(f"found {len(shard_files)} shard files")
        dfs = [pd.read_csv(f) for f in shard_files]
        return pd.concat(dfs, ignore_index=True)
    legacy = sorted(RAW.glob("*.csv"))
    if legacy:
        print(f"found {len(legacy)} legacy per-batch files")
        dfs = [pd.read_csv(f) for f in legacy]
        return pd.concat(dfs, ignore_index=True)
    # also check colab/shards downloads placed elsewhere
    alt = sorted((ROOT / "colab" / "shards").glob("ccx_phase1_shard*.csv"))
    if alt:
        # these are not results but if user hasn't moved them, warn
        print(f"warning: no files in {RAW}, found {len(alt)} in colab/shards — move them to {RAW}")
        dfs = [pd.read_csv(f) for f in alt]
        return pd.concat(dfs, ignore_index=True)
    raise FileNotFoundError(f"no Phase1 shard files in {RAW} (expected ccx_phase1_shard*.csv)")

def main():
    seeds_cfg = json.loads((ROOT / "configs" / "seeds.json").read_text())
    sub = seeds_cfg["phase1_inflation_subsample"]
    u = seeds_cfg["phase1_uniform"]

    df = load_shards()
    print(f"loaded {len(df)} rows from shards")

    # add vertices if not already present
    if not (df["source"] == "vertex").any():
        from models import iv_vertices, build_iv_A, discover_facets
        from src.enumeration import process_batch
        # need facets for process_batch
        from pathlib import Path as P
        # facets already in RES
        V = iv_vertices().astype(float)
        # use same process_batch logic but we can call it directly if available
        sys_path = str(ROOT / "src")
        import sys
        sys.path.insert(0, sys_path)
        from enumeration import process_batch as pb
        df_v = pd.DataFrame(pb(V, "vertex", -1, -1))
        df = pd.concat([df, df_v], ignore_index=True)
        print(f"added vertices, now {len(df)}")

    # inflation subsample (same logic as enumeration.py tail)
    ksub = max(1, (u["n_batches"] * u["batch_size"]) // sub["n_points"])
    mask = ((df["source"] == "uniform") & (df["batch"] % ksub == 0)) | \
           ((df["source"] == "boundary") & (df["batch"] % 5 == 0))
    idx_sub = df.index[mask].to_numpy()[:sub["n_points"]]
    print(f"inflation-2 subsample: {len(idx_sub)} instances")
    if len(idx_sub):
        from models import build_iv_A
        from witnesses import iv_inflation2_feasible
        A16 = build_iv_A()
        inf_res = []
        for i in idx_sub:
            e = df.loc[i, [f"e_{j}" for j in range(8)]].to_numpy(dtype=float)
            inf_res.append(iv_inflation2_feasible(e, A16))
        df.loc[idx_sub, "inflation2_feasible"] = np.array(inf_res, dtype=float)

    RES.mkdir(parents=True, exist_ok=True)
    df.to_csv(RES / "t1_dictionary.csv", index=False)
    print(f"wrote {RES / 't1_dictionary.csv'} ({len(df)} rows)")

    # hierarchy, strictness, redundancy — replicate enumeration.py tail
    ctx = df[(~df["lp_feasible"]) & (~df["borderline_band"])].copy()
    hier = pd.DataFrame({
        "instance_id": ctx["instance_id"],
        "strongly_contextual": ctx["cf1_hard"] < 1.0,
        "cf1_hard": ctx["cf1_hard"],
        "maximally_contextual": ctx["maximally_contextual"].astype(bool),
        "cf1_soft": ctx["cf1_soft"],
        "degree_honest": ctx["slack_l1"] / 2.0,
        "degree_signed": ctx["degree_signed"],
        "kl_contextuality": ctx["kl_contextuality"],
        "slack_l1": ctx["slack_l1"],
    })
    hier.to_csv(RES / "hierarchy_placement.csv", index=False)

    strict = pd.DataFrame({
        "instance_id": ctx["instance_id"],
        "nm_equalities_hold": True,
        "n_nm_constraints": 0,
        "margin_cf1_soft": 1.0 - ctx["cf1_soft"],
        "margin_degree_honest": ctx["slack_l1"] / 2.0,
        "margin_kl": ctx["kl_contextuality"],
    })
    strict["strict_instance"] = (strict["margin_cf1_soft"] >= 0.05) | \
                                 (strict["margin_degree_honest"] >= 0.05) | \
                                 (strict["margin_kl"] >= 0.05)
    strict.to_csv(RES / "strictness_scan.csv", index=False)

    from scipy.stats import spearmanr
    wit_cols = ["cf1_soft", "degree_signed", "kl_contextuality", "cf1_hard"]
    def safe_spearman(a, wcol):
        if len(a) < 3 or a[wcol].nunique() < 2 or a["slack_l1"].nunique() < 2:
            return np.nan
        return float(spearmanr(a[wcol], a["slack_l1"]).statistic)
    rows_r=[]
    d_all = df[df["slack_l1"].notna()]
    d_ctx = d_all[~d_all["lp_feasible"] & ~d_all["borderline_band"]]
    for wcol in wit_cols:
        dd = d_all[[wcol, "slack_l1"]].replace([np.inf], np.nan).dropna()
        rho_all = safe_spearman(dd, wcol)
        dc = d_ctx[[wcol, "slack_l1"]].replace([np.inf], np.nan).dropna()
        rho_ctx = safe_spearman(dc, wcol)
        flag=False; lin_r2=np.nan
        try:
            if len(dc)>10 and dc[wcol].nunique()>2:
                from sklearn.isotonic import IsotonicRegression
                rk_x=dc[wcol].rank().to_numpy(); rk_y=dc["slack_l1"].rank().to_numpy()
                def iso_r2(x,y):
                    pred=IsotonicRegression(out_of_bounds="clip").fit_transform(x,y)
                    ss_res=float(((y-pred)**2).sum()); ss_tot=float(((y-y.mean())**2).sum())
                    return 1-ss_res/ss_tot if ss_tot>0 else np.nan
                r_up=iso_r2(rk_x, rk_y); r_dn=iso_r2(-rk_x, rk_y)
                flag=bool(max(r_up,r_dn)>=0.9999)
            if wcol=="cf1_soft" and len(dc)>10:
                x=(1.0-dc[wcol]).to_numpy(); y=dc["slack_l1"].to_numpy()
                A_lin=np.vstack([x, np.ones_like(x)]).T
                coef, *_ = np.linalg.lstsq(A_lin, y, rcond=None)
                pred=A_lin@coef
                ss_res=float(((y-pred)**2).sum()); ss_tot=float(((y-y.mean())**2).sum())
                lin_r2=1-ss_res/ss_tot if ss_tot>0 else np.nan
        except Exception:
            flag=False
        rows_r.append({"witness": wcol, "spearman_rho": rho_all, "spearman_rho_contextual": rho_ctx,
                       "lin_r2_slack_vs_1_minus_witness": lin_r2, "n": int(len(dd)), "monotone_injective_flag": flag})
    pd.DataFrame(rows_r).to_csv(RES / "witness_lp_redundancy.csv", index=False)
    print("phase1 aggregation complete")
    print(pd.DataFrame(rows_r).to_string(index=False))

if __name__ == "__main__":
    main()
